version: "3"
services:
  redis-server:
    image: redis
    restart: unless-stopped
  node-sozluk:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis-server:6379
    restart: unless-stopped